# Generated by Django 4.1.5 on 2023-01-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Websites',
        ),
    ]
